//  TypeScript interfaces
// src/types/patient.types.ts
import type { Models } from 'appwrite';
export type PatientDocument = Models.Document & {
  userId: string;
  firstName: string;
  lastName: string;
  phone?: string;
  dateOfBirth: string;
  gender: 'male' | 'female' | 'other';
  medicalHistory?: string;
  address?: string;
  city?: string;
  isActivated: boolean;
};
export interface Patient {
  $id: string; // Appwrite document ID
  userId: string; // Appwrite Auth user ID
  firstName: string;
  lastName: string;
  phone?: string;
  dateOfBirth: string; // ISO 8601 datetime string from Appwrite
  gender: 'male' | 'female' | 'other';
  medicalHistory?: string;
  address?: string;
  city?: string;
  isActivated: boolean;
  $createdAt: string; // Auto-generated by Appwrite
  $updatedAt: string; // Auto-generated by Appwrite
}

export interface CreatePatientDTO {
  userId: string;
  firstName: string;
  lastName: string;
  phone?: string;
  dateOfBirth: string; // ISO 8601 format: "2000-01-15T00:00:00.000+00:00"
  gender: 'male' | 'female' | 'other';
  medicalHistory?: string;
  address?: string;
  city?: string;
  isActivated: boolean;
}

export interface UpdatePatientDTO {
  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: string;
  gender?: 'male' | 'female' | 'other';
  medicalHistory?: string;
  address?: string;
  city?: string;
}